[DOT-368] - fix gh;

diff --git a/.github/workflows/helm-update-gh-pages.yaml b/.github/workflows/helm-update-gh-pages.yaml
--- a/.github/workflows/helm-update-gh-pages.yaml
+++ b/.github/workflows/helm-update-gh-pages.yaml
@@ -40,13 +40,12 @@ jobs:
           DOWNLOAD_URL="https://github.com/helm/chart-releaser/releases/download/v${CR_VERSION}/${CR_BINARY}"
 
           echo "Downloading Chart Releaser from $DOWNLOAD_URL"
-          if ! curl --head --fail --silent "$DOWNLOAD_URL"; then
-            echo "Error: The requested file does not exist at $DOWNLOAD_URL"
-            exit 1
-          fi
-          
-          curl -fsSL -o cr.tar.gz "$DOWNLOAD_URL"
-          tar -xzf cr.tar.gz
+          curl -fsSL -o cr.tar.gz -L "$DOWNLOAD_URL" || { echo "Failed to download"; exit 1; }
+
+          echo "Extracting Chart Releaser..."
+          tar -xzf cr.tar.gz || { echo "Failed to extract"; exit 1; }
+
+          echo "Moving binary to /usr/local/bin"
           chmod +x chart-releaser
           sudo mv chart-releaser /usr/local/bin/cr
 
